Claimdrops Smart Contract
hive-engine/steemsmartcontracts pull request #24
Opened 2020-11-14 12:41 UTC by ali-h

2020-11-16 16:09 UTC, donchate commented
A nice option would be to distribute unclaimed pool amount to those who claimed.

2020-11-17 00:40 UTC, bt-cryptomancer requested changes
This mostly looks good.  I think it would be good to have a bit stricter validation on max size limits, see comments at indicated code sections.

I'd also like to avoid adding another virtual transaction to Block.js, as we already have several of those and I don't want to add any more unless absolutely necessary.  Let's have checkExpiredClaimdrops be called first whenever someone uses the claim action.  And it would be good to have an expire action that only the claimdrop owner can use, so the owner can manually trigger expiration when desired, instead of waiting for the next claim action to do it.

2020-11-17 00:40 UTC, bt-cryptomancer commented on contracts/claimdrops.js
> +      && api.assert(api.BigNumber(limit).gt(0), `list[${i}]: limit must be positive`)
Can you do a max size check for limit?  Can be something like asserting that api.BigNumber(limit).lte(Number.MAX_SAFE_INTEGER) and also use the BigNumber isFinite function - https://mikemcl.github.io/bignumber.js/#isF

2020-11-17 00:40 UTC, bt-cryptomancer commented on contracts/claimdrops.js
> +      && maxClaims && Number.isInteger(maxClaims)
Can you do a max size check for maxClaims?  Should make sure it is less than Number.MAX_SAFE_INTEGER

2020-11-17 00:40 UTC, bt-cryptomancer commented on contracts/claimdrops.js
> +          if (api.assert(api.BigNumber(limit).gt(0), 'limit must be positive')
Can you do a max size check for limit? Can be something like asserting that api.BigNumber(limit).lte(Number.MAX_SAFE_INTEGER) and also use the BigNumber isFinite function - https://mikemcl.github.io/bignumber.js/#isF

2020-11-17 00:44 UTC, bt-cryptomancer commented
> A nice option to add would be to distribute unclaimed pool amount to those who claimed.

Agreed, I don't think this is necessary for the first version of the contract, but would be a cool feature to add in a version 2 release.

2020-11-17 05:54 UTC, ali-h commented
> A nice option to add would be to distribute unclaimed pool amount to those who claimed.

a nice feature, this can surely be added in the next version as an optional choice for the owner.

2020-11-17 08:18 UTC, ali-h commented
> This mostly looks good. I think it would be good to have a bit stricter validation on max size limits, see comments at indicated code sections.
> 
> I'd also like to avoid adding another virtual transaction to Block.js, as we already have several of those and I don't want to add any more unless absolutely necessary. Let's have checkExpiredClaimdrops be called first whenever someone uses the claim action. And it would be good to have an expire action that only the claimdrop owner can use, so the owner can manually trigger expiration when desired, instead of waiting for the next claim action to do it.

I've added stricter validations so its less than MAX_SAFE_INTEGER but is `isFinite` necessary? if the value is less than safe integer its finite right.

Yes, initially I was going to add expireClaimdrops in the claim action, but thought it might get the processing slow? but its probably better than adding virtual transaction every block for it. so not searching for all expired claimdrops, now when a claim action is called, if the requested claimdrop has reached its expiration time it gets deleted (the expire action triggers).

I've modified `checkExpiredClaimdrops`  to be `expire` which can be called by the sender or owner set by the sender of a claimdrop, this gives the option to expire a claimdrop manually anytime without depending on claim action.

I've added sender and owner both to the claimdrop object because maybe if the owner is a contract it can not call expire event.

2020-11-19 01:58 UTC, bt-cryptomancer requested changes
> I've added stricter validations so its less than MAX_SAFE_INTEGER but is isFinite necessary? if the value is less than safe integer its finite right.

eonwarped started using isFinite in his contract code, which I thought was a nice idea, but you're right that's a redundant check since you're comparing with Number.MAX_SAFE_INTEGER anyway.  So this is fine.

> Yes, initially I was going to add expireClaimdrops in the claim action, but thought it might get the processing slow? but its probably better than adding virtual transaction every block for it. so not searching for all expired claimdrops, now when a claim action is called, if the requested claimdrop has reached its expiration time it gets deleted (the expire action triggers).

Expiring a claimdrop is a pretty cheap operation, so I'd still like to see a claim operation expire all old claimdrops, not just the one being claimed.  The market contract works similarly; when a market order is placed, it removes all old orders which have already expired.

All other changes look fine.

2020-11-24 02:12 UTC, bt-cryptomancer requested changes
The way you've got the removeExpiredClaimdrops function coded now introduces the possibility of non-deterministic behavior.  Although this is extremely unlikely with this kind of contract, it's still something that needs to be handled properly.  The problem is that api.db.find implicitly limits query results to 1000 when you don't explicitly provide the limit parameter.  Thus if there are more than 1000 expired claimdrops, this code won't work as intended (and without using indexes on the query, the order of query results is not well defined).

I see 2 options to fix this problem:

1.  Add back in the maxExpiresPerBlock setting that you originally had, as well as the use of the _id index.

OR

2. Wrap the query in a while loop to ensure the case of > 1000 query results is handled OK.  For an example of this technique, see the actions.checkPendingUndelegations function in nft.js or upgradeUserSchema function in botcontroller.js

2020-11-24 04:12 UTC, bt-cryptomancer commented
Of the two options I suggested to resolve the query issue, if using number 2 I think it's still important to make sure an index is used for sorting.  We probably should do an audit of the other contracts at some point and ensure indexes are always being used, or else change the core node software to always add the _id index if one is not specified.

2020-11-24 04:37 UTC, ali-h commented
changes made. I did think about this but got up with the likely scenario. but yup contracts can be abused if there are no checks for things like this. I've added similar loop to `checkPendingUndelegations` in nft contract where loop continues if there are more than 1000 objects in the db with sorting by _id.

2020-11-24 04:43 UTC, bt-cryptomancer approved these changes
changes look good

2020-11-25 00:36 UTC, merged