(SMT) comment contract implementation
hive-engine/steemsmartcontracts pull request #54
Opened 2021-03-21 05:46 UTC by eonwarped

Adds comment contract, ability to set up post/comment reward pool.

Notes:
* Primary key functionality added to facilitate quick lookups. Compounded Indexes added to provide efficient sorting given fixed parameters (e.g. reward pool ID in this case) 
* Trending score computation and curve computations for post exponents other than 1 or 2, and curation exponents other than 0.5 or 1 use double precision float computation.
* Downvotes and upvotes use different pools, unlike hive's implementation where downvote power can bleed into the upvote power. It also uses the older voting power system (without mana) that requires powered up stake to charge before use.

2021-04-24 10:50 UTC, bt-cryptomancer requested changes
Mostly looks good, I didn't check the math carefully will assume you've tested all that thoroughly, just have some questions about some of the DB queries (see comments).  Also, you've got some lint errors to fix.

How has performance been in your test environment?  Is your node able to keep up with blocks OK, processing all the votes & comments, without lagging behind at all?

2021-04-25 14:10 UTC, eonwarped commented on contracts/comments.js
> +    const parentPosts = await api.db.find('posts', { authorperm: parentAuthorperm });
Yes, there is a cap that should be well less than 1000. I should probably add the cap explicitly as a param though.  I am planning on setting it to 20. (20 smt's linked to a post at most)

2021-04-25 14:11 UTC, eonwarped commented on contracts/comments.js
> +    const tagRewardPools = await api.db.find('rewardPools', { 'config.tags': { $in: jsonMetadata.tags } });
same

2021-04-25 14:15 UTC, eonwarped commented on contracts/comments.js
> +  const posts = await api.db.find('posts', { authorperm });
same

2021-04-25 14:16 UTC, eonwarped commented on contracts/comments.js
> +  const existingPosts = await api.db.find('posts', { authorperm });
same

2021-04-25 14:17 UTC, eonwarped commented on contracts/comments.js
> +                contractName: 'comments',
removed

2021-04-25 14:21 UTC, eonwarped commented
> Mostly looks good, I didn't check the math carefully will assume you've tested all that thoroughly, just have some questions about some of the DB queries (see comments). Also, you've got some lint errors to fix.
> 
> How has performance been in your test environment? Is your node able to keep up with blocks OK, processing all the votes & comments, without lagging behind at all?

Performance has been good, but I need to add more pools to my test to confirm.

2021-04-26 02:01 UTC, bt-cryptomancer approved these changes
Changes look good, will wait to merge until witness review period is finished.

2021-05-01 06:35 UTC, bt-cryptomancer approved these changes
Latest changes look good.

2021-05-04 09:42 UTC, bt-cryptomancer submitted a review, later dismissed
Latest changes look good.

2021-05-11 00:04 UTC, bt-cryptomancer approved these changes
Approved.

2021-05-18 09:06 UTC, bt-cryptomancer approved these changes
Latest changes look good.

2021-05-19 00:05 UTC, bt-cryptomancer approved these changes
updateFee change from 100 BEE to 20 BEE looks good.

2021-05-22 02:29 UTC, merged