NFT mining equip fields and extra mining power fields
hive-engine/steemsmartcontracts pull request #84
Opened 2021-07-27 16:36 UTC by eonwarped

Allow specifying equip field or mining power field to allow NFT creator to control what is considered as equipped and allow for extra mining power to be added per nft instance.

These can configured independently, and cannot be changed once a reward pool is created.

We add a new contract call from nft contract to mining contract whenever setProperties is called, which allows for the corresponding mining power to be updated.

2021-08-06 01:15 UTC, bt-cryptomancer requested changes
Only a couple small suggestions for improvement (see comments on specific lines of code).  Also, there's an error with one of the nft contract test cases (the "does not set data properties" test), so please fix that.

![image](https://user-images.githubusercontent.com/8011332/128441129-8dc04dfd-29b1-419f-9593-4402f11c8389.png)

2021-08-06 01:15 UTC, bt-cryptomancer commented on contracts/nft.js
> +            if (shouldUpdate) {
One optimization here would be to call the handleNftSetProperty action only if the data property value has actually changed.  If the new value is same as old value, no need to call this.  It's a small thing, but even loading & calling the other contract has some processing cost and saving every little bit helps.

2021-08-07 03:53 UTC, eonwarped commented
changes made. PTAL

2021-08-12 01:55 UTC, bt-cryptomancer approved these changes
Changes look good.

2021-08-13 02:17 UTC, merged